openapi: 3.0.0
info:
  title: User Authentication API
  description: API for user registration and login.
  version: 1.0.0

paths:
  /api/v1/auth/register:
    post:
      summary: Register a new user.
      description: Creates a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
                - confirmPassword
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        201:
          description: User created successfully.
        400:
          description: Invalid request.
        409:
          description: Username or email already exists.

  /api/v1/auth/login:
    post:
      summary: Login an existing user.
      description: Authenticates an existing user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login successful.
        401:
          description: Invalid credentials.
        404:
          description: User not found.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT